%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Homad\Documents\MATLAB\MILP_in_MATLAB_Webinar\UnitCommitment\info.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/05/02 23:52:23

%% Import the data
[~, ~, raw] = xlsread('C:\Users\Homad\Documents\MATLAB\MILP_in_MATLAB_Webinar\UnitCommitment\info.xlsx','Sheet1','A2:N8');
stringVectors = string(raw(:,1));
stringVectors(ismissing(stringVectors)) = '';
raw = raw(:,[2,3,4,5,6,7,8,9,10,11,12,13,14]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
info = table;

%% Allocate imported array to column variable names
info.Tech_Fuel = stringVectors(:,1);
info.CapacityGW = data(:,1);
info.NumberofUnits = data(:,2);
info.SizeofUnitMW = data(:,3);
info.CAPEXMSRGW = data(:,4);
info.FuelcostMSRGWh = data(:,5);
info.RampUpLimitMWhr = data(:,6);
info.RampDownLimitMWhr = data(:,7);
info.VariableOMMSRGWh = data(:,8);
info.StartUpCostMSRswitch = data(:,9);
info.MinimumUpTimehr = data(:,10);
info.MinimumDownTimehr = data(:,11);
info.MaxGenerationGW = data(:,12);
info.MinGenerationMW = data(:,13);

%% Clear temporary variables
clearvars data raw stringVectors;